### ISSUE TITLE
Implement API executor

### ISSUE THREAD

**Issue by devshorts** [paradoxical-io/aetr#11]
We should pull in some http library that provides statistics easily (that also lets us hit random endpoints) and wire in a executor

**Comment by chrisbenincasa** [comment]
https://github.com/AsyncHttpClient/async-http-client was pretty simple to setup. Netty-based too and we can override the default run loop group so that it just reuses FInagle's run loop.

**Comment by devshorts** [comment]
Is it worth pulling in Netty for what is really just a simple one off call? I was thinking we could probably get away with http4s. Down for either but we literally just need to execute a single POST to rando urls
