### ISSUE TITLE
NoOp task should auto complete when executed

### ISSUE THREAD

**Issue by devshorts** [paradoxical-io/aetr#7]

**Comment by chrisbenincasa** [comment]
Is this done? 

https://github.com/paradoxical-io/aetr/blob/3ae4c222cf2273f54b59f7ae36f82276789587ad/core/src/main/scala/io/paradoxical/aetr/core/execution/ExecutionHandler.scala#L26-L27

**Comment by devshorts** [comment]
Ya we should close it. We should however make the executor catch any exceptions and set the state as error
